const ORDER_STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  PREPARED: 'PREPARED',
  DELIVERED: 'DELIVERED',
}

const RESOURCE_STATUS = {
  BUSY: 'BUSY',
  AVAILABLE: 'AVAILABLE',
  NOT_AVAILABLE: 'NOT-AVAILABLE',
}

module.exports = {
  ORDER_STATUS,
  RESOURCE_STATUS,
}